# Generated by Django 5.2.3 on 2025-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='schoolyear',
            field=models.CharField(default=0.96),
            preserve_default=False,
        ),
    ]
