# Generated by Django 5.2.3 on 2025-07-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schoolyear_schoolyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolyear',
            old_name='user_id',
            new_name='user',
        ),
    ]
