# Generated by Django 5.2.3 on 2025-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_outofserviceday_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='weekends',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
