# Generated by Django 5.2.3 on 2025-07-23 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_schoolyear_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.schoolyear'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.class'),
        ),
    ]
