# Generated by Django 5.2.3 on 2025-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_class_school_year_alter_unit_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
