# Generated by Django 5.2.3 on 2025-07-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_class_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='user_id',
            new_name='user',
        ),
    ]
