# Generated by Django 5.2.3 on 2025-07-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_id_class_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='class_id',
        ),
        migrations.AddField(
            model_name='unit',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='api.class'),
        ),
    ]
