# Generated by Django 5.2.3 on 2025-07-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_unit_class_id_unit__class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='_class',
            new_name='class_obj',
        ),
    ]
