# Generated by Django 5.2.3 on 2025-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename__class_unit_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
