# Generated by Django 5.2.3 on 2025-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_unit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
