# Generated by Django 5.2.3 on 2025-07-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_unit_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
